export const setSidebarEvents = () => ({ type: 'SIDEBAR_EVENTS' })
export const setSidebarReport = () => ({ type: 'SIDEBAR_REPORT' })
export const setSidebarColletions = () => ({ type: 'SIDEBAR_COLLECTIONS' })
export const setSidebarCataTreco = () => ({ type: 'SIDEBAR_CATATRECO' })
export const setSidebarLei = () => ({ type: 'SIDEBAR_LEI' })